

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_literals_to_create_immutables: false
    prefer_typing_uninitialized_variables: false
    prefer_const_constructors: false
    non_constant_identifier_names: false
    file_names: false
    must_be_immutable: false
    prefer_interpolation_to_compose_strings: false
    use_build_context_synchronously: false
    avoid_function_literals_in_foreach_calls: false
    unnecessary_new: false
    depend_on_referenced_packages: false